name: Destroy {{ cookiecutter.project_name }}

on:
  # push:
  #   branches:
  #     - {{ cookiecutter.default_branch }}
  workflow_dispatch:

env:
  AWS_REGION: { { cookiecutter.region } }
  TERRAFORM_VERSION: { { cookiecutter.terraform_version } }
  WORKING_DIRECTORY: .

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    environment: { { cookiecutter.environment } }

    permissions:
      id-token: write
      contents: read
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ '{{' }} secrets.SANDBOX_AWS_ROLE_TO_ASSUME {{ '}}' }}
          aws-region: ${{ '{{' }} env.AWS_REGION {{ '}}' }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ '{{' }} env.TERRAFORM_VERSION {{ '}}' }}

      - name: Terraform Init
        working-directory: ${{ '{{' }} env.WORKING_DIRECTORY {{ '}}' }}
        run: terraform init

      - name: Terraform Destroy
        working-directory: ${{ '{{' }} env.WORKING_DIRECTORY {{ '}}' }}
        run: terraform apply -auto-approve
